---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install pip
  ansible.builtin.apt:
    name: pip
    state: present

- name: Install virtualenv
  ansible.builtin.apt:
    name: virtualenv
    state: present

- name: Install ffmpeg
  ansible.builtin.apt:
    name: ffmpeg
    state: present

- name: Create venv dir
  file:
    path: /home/pc/venv
    state: directory