---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Install pulseaudio
  ansible.builtin.apt:
    name: pulseaudio
    state: present

- name: Install pulseaudio bluetooth
  ansible.builtin.apt:
    name: pulseaudio-module-bluetooth
    state: present

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present

- name: Install expect
  ansible.builtin.apt:
    name: expect
    state: present

- name: Install ffmpeg
  ansible.builtin.apt:
    name: ffmpeg
    state: present

- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker

- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
    state: present
  tags:
    - docker

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add remote "pc" user to "docker" group
  user:
    name: "pc"
    groups: "docker"
    append: yes
  tags:
    - docker

- name: Reset every night at 03:30 AM 
  lineinfile:
    path: /var/spool/cron/crontabs/root
    line: "30 3 * * * /sbin/shutdown -r now"
    create: yes

# UV4L UNCOMMENT FOR WEB-RTC
- name: Create bin dir
  file:
    path: /home/pc/bin
    state: directory
    mode: "0755"

- name: Deploy the uv4l install script
  ansible.builtin.copy:
    src: ../../res/bin/install_uv4l.sh
    dest: /home/pc/bin/install_uv4l.sh
    owner: pc
    group: pc
    mode: '0744'

- name: Deploy the connect_bluetooth script
  ansible.builtin.copy:
    src: ../../res/bin/connect_bluetooth.sh
    dest:  /home/pc/bin/connect_bluetooth.sh
    owner: pc
    group: pc
    mode: '0744'
